### ISSUE TITLE
migrate to using dynamic inventory for AWS instances

### ISSUE THREAD

**Issue by ess-acppo** [ess-acppo/nsl-infra#5]
Currently, ansible uses static inventory files to manage AWS instances which is not at all ideal. Use dynamic inventory instead.

**Comment by ArnabRaxit** [comment]
Work on this has been completed. It is now possible to provision an entirely fresh set of AWS resources to server as a new environment.

**Comment by moziauddin1** [comment]
This is completed. All playbooks now use dynamic inventory files for ansible provisioning and instance targetting
