### ISSUE TITLE
Failover strategy

### ISSUE THREAD

**Issue by ArnabRaxit** [ess-acppo/nsl-infra#7]
1. ASG with min=max=1 instance
2. Take a backup of the instance as AMI every 5 mins.
3. Update launch configuration with latest AMI.  ( _since AWS doesn't support editing launch configs; create a new one and attach to the ASG)_

With this strategy, MTTR is  &#8776; 4 mins

**Comment by moziauddin1** [comment]
We are not using ASG/LC now as the application is now backed up on daily basis. And pgdump every two hours (planned). The project team has determined this to be acceptable level of availability for this application.
